# Generated by Django 5.2.6 on 2025-09-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quizattempt",
            options={"ordering": ["-completed_at"]},
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
