# Generated by Django 5.2.6 on 2025-09-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_alter_quizattempt_options_alter_quizattempt_score"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentbadge",
            options={"ordering": ["-awarded_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="quizattempt",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="attempt_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="score",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="quizattempt",
            unique_together={("student", "quiz", "attempt_number")},
        ),
    ]
