# Generated by Django 5.2.6 on 2025-09-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_alter_studentbadge_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizattempt",
            name="score",
            field=models.FloatField(default=0),
        ),
    ]
