# Generated by Django 5.2.6 on 2025-09-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_alter_quizattempt_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizattempt",
            name="attempt_number",
            field=models.PositiveIntegerField(),
        ),
    ]
