# Generated by Django 5.2.6 on 2025-09-23 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_classroom_enrollment_classroom_students"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("digital_literacy", "Digital Literacy"),
                            ("stem", "STEM Subjects"),
                            ("mathematics", "Mathematics"),
                            ("physics", "Physics"),
                            ("chemistry", "Chemistry"),
                            ("biology", "Biology"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_hi", models.CharField(blank=True, max_length=200)),
                ("title_pa", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField()),
                ("description_hi", models.TextField(blank=True)),
                ("description_pa", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("video_url_en", models.URLField(blank=True)),
                ("video_url_hi", models.URLField(blank=True)),
                ("video_url_pa", models.URLField(blank=True)),
                (
                    "video_file_en",
                    models.FileField(blank=True, upload_to="videos/english/"),
                ),
                (
                    "video_file_hi",
                    models.FileField(blank=True, upload_to="videos/hindi/"),
                ),
                (
                    "video_file_pa",
                    models.FileField(blank=True, upload_to="videos/punjabi/"),
                ),
                ("duration_minutes", models.IntegerField(default=10)),
                ("thumbnail_url", models.URLField(blank=True)),
                ("view_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="quiz.videocategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("watch_time_seconds", models.IntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                ("completion_percentage", models.FloatField(default=0.0)),
                ("preferred_language", models.CharField(default="en", max_length=5)),
                ("first_watched", models.DateTimeField(auto_now_add=True)),
                ("last_watched", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.student"
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.video"
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "video")},
            },
        ),
    ]
